version: '3.8'

services:
  mariadb:
    image: mariadb:10.6
    container_name: library_db_dev
    restart: always
    ports:
      - "3306:3306"  
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: quan_ly_thu_vien
      MYSQL_USER: admin
      MYSQL_PASSWORD: password!
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
